# Generated by Django 6.0.3 on 2026-05-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
    ]
